In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("post_eda_glo.csv")

In [4]:
df["EXPANSION_PERCENTILE"] = (
    df["EXPANSION_RATE"]
    .rank(pct=True) * 100
)

In [5]:
df.head(10)

,geometry,GLO_ID,COUNTRY,BASIN,CONNECTIVITY,DATA_SOURCE,EXPANSION_RATE,EXPANSION_UNCERTAINTY,EXPANSION_RATE_SIG,S2_MSTAT,...,LATITUDE,GTNG_REGION_O2,ELEVATION_MIN,ELEVATION_MEDIAN,ELEVATION_MEAN,AREA_DISSOLVED,PERIMETER_DISSOLVED,SIGNIFICANT_EXPANSION,LOG_AREA,EXPANSION_PERCENTILE
0,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1335...",GLO_80.03311_30.32452,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,30.32452,15-01,4887.0,4888.483007,4888.430176,0.008259,0.429067,0,0.008225,49.747219
1,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1334...",GLO_80.04206_30.3709,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,30.37087,15-01,4589.0,4608.617580,4607.427734,0.008255,0.471461,0,0.008221,49.747219
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05413_30.37819,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,30.37819,15-01,4504.0,4509.000000,4513.311523,0.001290,0.166014,0,0.001289,49.747219
3,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05556_30.37113,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,30.37113,15-01,4476.0,4476.500000,4476.208984,0.008269,0.547027,0,0.008235,49.747219
4,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.07262_30.33587,India,Karnali,Glacier-fed,Sentinel-1,0.0041,0.0057,False,1.0,...,30.33669,15-01,4191.0,4201.754220,4206.367676,0.080575,1.709878,False,0.077493,97.472194
5,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1326...",GLO_80.10457_30.47975,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,30.47975,15-01,3769.0,3779.607557,3779.372803,0.007731,0.454022,0,0.007701,49.747219
6,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1329...",GLO_80.13083_30.20429,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,30.20432,15-01,4475.0,4477.453427,4477.936523,0.019553,0.664655,0,0.019364,49.747219
7,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1328...",GLO_80.13634_30.21008,India,Karnali,Glacier-fed,Sentinel-1,0.0001,0.0073,False,1.0,...,30.21003,15-01,4326.0,4348.353184,4348.479980,0.113177,1.831956,False,0.107218,70.121335
8,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1322...",GLO_80.15577_30.48392,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,30.48419,15-01,5054.0,5059.669775,5060.231445,0.007902,0.408846,0,0.007871,49.747219
9,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1318...",GLO_80.17695_30.56435,India,Karnali,Glacier-fed,Sentinel-1,0.0070,0.0100,False,1.0,...,30.56425,15-01,4864.0,4875.461655,4893.459961,0.330611,4.152602,False,0.285638,98.281092

In [6]:
df["AREA_PERCENTILE"] = (
    df["AREA_DISSOLVED"]
    .rank(pct=True) * 100
)

In [7]:
df.head(10)

,geometry,GLO_ID,COUNTRY,BASIN,CONNECTIVITY,DATA_SOURCE,EXPANSION_RATE,EXPANSION_UNCERTAINTY,EXPANSION_RATE_SIG,S2_MSTAT,...,GTNG_REGION_O2,ELEVATION_MIN,ELEVATION_MEDIAN,ELEVATION_MEAN,AREA_DISSOLVED,PERIMETER_DISSOLVED,SIGNIFICANT_EXPANSION,LOG_AREA,EXPANSION_PERCENTILE,AREA_PERCENTILE
0,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1335...",GLO_80.03311_30.32452,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,15-01,4887.0,4888.483007,4888.430176,0.008259,0.429067,0,0.008225,49.747219,26.390293
1,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1334...",GLO_80.04206_30.3709,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,15-01,4589.0,4608.617580,4607.427734,0.008255,0.471461,0,0.008221,49.747219,26.322885
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05413_30.37819,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,15-01,4504.0,4509.000000,4513.311523,0.001290,0.166014,0,0.001289,49.747219,1.044826
3,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05556_30.37113,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,15-01,4476.0,4476.500000,4476.208984,0.008269,0.547027,0,0.008235,49.747219,26.525110
4,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.07262_30.33587,India,Karnali,Glacier-fed,Sentinel-1,0.0041,0.0057,False,1.0,...,15-01,4191.0,4201.754220,4206.367676,0.080575,1.709878,False,0.077493,97.472194,85.069093
5,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1326...",GLO_80.10457_30.47975,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,15-01,3769.0,3779.607557,3779.372803,0.007731,0.454022,0,0.007701,49.747219,24.165824
6,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1329...",GLO_80.13083_30.20429,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,15-01,4475.0,4477.453427,4477.936523,0.019553,0.664655,0,0.019364,49.747219,51.432423
7,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1328...",GLO_80.13634_30.21008,India,Karnali,Glacier-fed,Sentinel-1,0.0001,0.0073,False,1.0,...,15-01,4326.0,4348.353184,4348.479980,0.113177,1.831956,False,0.107218,70.121335,89.349511
8,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1322...",GLO_80.15577_30.48392,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,15-01,5054.0,5059.669775,5060.231445,0.007902,0.408846,0,0.007871,49.747219,24.907314
9,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1318...",GLO_80.17695_30.56435,India,Karnali,Glacier-fed,Sentinel-1,0.0070,0.0100,False,1.0,...,15-01,4864.0,4875.461655,4893.459961,0.330611,4.152602,False,0.285638,98.281092,96.798113

In [8]:
df["GLACIER_CONNECTIVITY_SCORE"] = (
    df["CONNECTIVITY"]
    .eq("Glacier-fed")
    .astype(int) * 100
)
df.head()

,geometry,GLO_ID,COUNTRY,BASIN,CONNECTIVITY,DATA_SOURCE,EXPANSION_RATE,EXPANSION_UNCERTAINTY,EXPANSION_RATE_SIG,S2_MSTAT,...,ELEVATION_MIN,ELEVATION_MEDIAN,ELEVATION_MEAN,AREA_DISSOLVED,PERIMETER_DISSOLVED,SIGNIFICANT_EXPANSION,LOG_AREA,EXPANSION_PERCENTILE,AREA_PERCENTILE,GLACIER_CONNECTIVITY_SCORE
0,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1335...",GLO_80.03311_30.32452,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,4887.0,4888.483007,4888.430176,0.008259,0.429067,0,0.008225,49.747219,26.390293,100
1,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1334...",GLO_80.04206_30.3709,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,4589.0,4608.617580,4607.427734,0.008255,0.471461,0,0.008221,49.747219,26.322885,100
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05413_30.37819,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,4504.0,4509.000000,4513.311523,0.001290,0.166014,0,0.001289,49.747219,1.044826,100
3,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05556_30.37113,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,4476.0,4476.500000,4476.208984,0.008269,0.547027,0,0.008235,49.747219,26.525110,100
4,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.07262_30.33587,India,Karnali,Glacier-fed,Sentinel-1,0.0041,0.0057,False,1.0,...,4191.0,4201.754220,4206.367676,0.080575,1.709878,False,0.077493,97.472194,85.069093,100

In [9]:
df["SIGNIFICANCE_SCORE"] = (
    df["EXPANSION_RATE_SIG"]
    .notna()
    .astype(int) * 100
)

In [10]:
df.head()

,geometry,GLO_ID,COUNTRY,BASIN,CONNECTIVITY,DATA_SOURCE,EXPANSION_RATE,EXPANSION_UNCERTAINTY,EXPANSION_RATE_SIG,S2_MSTAT,...,ELEVATION_MEDIAN,ELEVATION_MEAN,AREA_DISSOLVED,PERIMETER_DISSOLVED,SIGNIFICANT_EXPANSION,LOG_AREA,EXPANSION_PERCENTILE,AREA_PERCENTILE,GLACIER_CONNECTIVITY_SCORE,SIGNIFICANCE_SCORE
0,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1335...",GLO_80.03311_30.32452,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,4888.483007,4888.430176,0.008259,0.429067,0,0.008225,49.747219,26.390293,100,0
1,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1334...",GLO_80.04206_30.3709,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,1.0,...,4608.617580,4607.427734,0.008255,0.471461,0,0.008221,49.747219,26.322885,100,0
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05413_30.37819,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,4509.000000,4513.311523,0.001290,0.166014,0,0.001289,49.747219,1.044826,100,0
3,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.05556_30.37113,India,Karnali,Glacier-fed,Sentinel-1,0.0000,0.0000,NaN,0.0,...,4476.500000,4476.208984,0.008269,0.547027,0,0.008235,49.747219,26.525110,100,0
4,"{""type"":""MultiPolygon"",""coordinates"":[[[[-1332...",GLO_80.07262_30.33587,India,Karnali,Glacier-fed,Sentinel-1,0.0041,0.0057,False,1.0,...,4201.754220,4206.367676,0.080575,1.709878,False,0.077493,97.472194,85.069093,100,100

In [29]:
df1 = df.copy()
cluster_features = df[['LOG_AREA',
                    'EXPANSION_PERCENTILE',
                    'AREA_PERCENTILE',
                    'GLACIER_CONNECTIVITY_SCORE',
                    'SIGNIFICANCE_SCORE']]

In [30]:
cluster_features.head()

,LOG_AREA,EXPANSION_PERCENTILE,AREA_PERCENTILE,GLACIER_CONNECTIVITY_SCORE,SIGNIFICANCE_SCORE
0,0.008225,49.747219,26.390293,100,0
1,0.008221,49.747219,26.322885,100,0
2,0.001289,49.747219,1.044826,100,0
3,0.008235,49.747219,26.525110,100,0
4,0.077493,97.472194,85.069093,100,100

In [ ]:
cluster_features.to_csv(
    "processed_ufc_fights\.csv",
    index=False
)